### ISSUE TITLE
Don't work - LUA ERROR

### ISSUE THREAD

**Issue by metz1996** [Bobster82/FS22_AutoRepair#1]
The Mod does not work. Would love to use it but it cause LUA Error's and don't repair
```
FS22_AutoRepair/AutoRepair.lua:47: attempt to call method 'getDamageAmount' (a nil value)
Error: Running LUA method 'update'.
```

**Comment by Bobster82** [comment]
Can you post your savegame vehicle.xml ?
Maybe there are vehicles types that needed to be added...

**Comment by metz1996** [comment]
https://pastebin.com/B52PGQEN
Here

**Comment by Bobster82** [comment]
Thanks, I think I found the problem, will need to check how to fix... wil let you know when i have it fixed

**Comment by metz1996** [comment]
Thanks for the fast respond :) would be amazing to have your Mod working :)

**Comment by Bobster82** [comment]
Can you test with the new version? It should be ok.
https://github.com/Bobster82/FS22_AutoRepair/blob/master/Release/FS22_AutoRepair.zip

**Comment by metz1996** [comment]
Sure. I did. I tried it on the same offline Savegame. It worked fine, no error's in log. Now i will upload it to my dedicated server and try it there. Looks fine. 

With your "old" Version after 0:00 the game freezed or better explained: If you press "W" your Key will stuck and the game get unplayable. With the new one it worked fine. When i tested it on my dedicated Server i will let you know

**Comment by metz1996** [comment]
Ok i testet it on my server. It work's well. Thank's for your work!

Do it repair at random time? I thought your Mod in FS19 repaired once a day at 0:00

**Comment by Bobster82** [comment]
Nice. Thanks for testing.
No problem, its my mod, so I need to give suport ;)

It repairs when vehicles or tools have 5% or more damage. This way your equipment stays healthy.

**Comment by metz1996** [comment]
Ok. So it's a bit different like your Mod in FS19? Because there it repaired at 0:00

You don't have to offer support. Because you don't earn money with that :) But nice that you do it.
I appreciate your work very much

Was the Problem that it tried to repair a pallet? :D

**Comment by Bobster82** [comment]
Yes, a bit different. I think way better.

Money or not, it still needs to work haha. I dont mind doing it, I like when people enjoy it. So thats worth something ;)

Yes the tree pallet gave the problem, it has a different typename... you cant test it all haha
