### ISSUE TITLE
autorepair does only work once after install

### ISSUE THREAD

**Issue by netserver238** [Bobster82/FS22_AutoRepair#10]
Hi Bobster82,

recently using FS22_AutoRepair 2.0.0.5 on FS22 1.10.1.1 (local single player)
downloaded the zip file from this site, moved into mod folder, started FS22, aktivated mod on start screen, entered menu with alt+r, set autorepair at 70%, every vehicle or attachment has been repaired and costs were shown, so far so good. but later in game when vehicles are used or after restart nothing happens when repair reached desired repair %. After deleting and reinstall same issue, repair worked only once. log shows only one error entry:
"2023-06-26 16:51 Warning: Character '9' not found in texture font (2023-06-26 16:51 	2023-06-26 16:51  in 2023-06-26 16:51  AutoRepair hält Ihr Fahrzeug gesund."
any idea or solution? how can I provide more info?

**Comment by Bobster82** [comment]
Can u drop the complete log.txt file ?
I just did a test run and I didnt see any issues.
I don't really update this mod anymore, but I can take a look what the problem might be ;)

**Comment by netserver238** [comment]
[log.txt](https://github.com/Bobster82/FS22_AutoRepair/files/11879668/log.txt)

thx for ur support

**Comment by Bobster82** [comment]
I couldn't see any errors in the log from my mod. But I see a lot of other errors from other mods, maybe they're the problem.
If you remove all mods except mine, does the problem still exists?

**Comment by netserver238** [comment]
found the error, ur script is fine, brainlag due high temperature, misinterpreted the damage value in your menu with condition of the vehicle in the overview. so, as entering "70" I expected repair at 70% condition and not 70% dmg...
nevertheless I appreciate your fast respond - have a good time!

**Comment by Bobster82** [comment]
> found the error, ur script is fine, brainlag due high temperature, misinterpreted the damage value in your menu with condition of the vehicle in the overview. so, as entering "70" I expected repair at 70% condition and not 70% dmg... nevertheless I appreciate your fast respond - have a good time!

Great u found the problem, glad its not my script ;)
U too have a good time! And have fun farming!
