### ISSUE TITLE
Version 2.0.0.3

### ISSUE THREAD

**Issue by Bobster82** [Bobster82/FS22_AutoRepair#3]
Hi,

New version added with repainting and cleaning as extra options.

The new version needs some MultiPlayer testing, as I cant test that.
If someone can confirm this is working as aspected, let me know ;)

Thank you!

**Comment by Tobias0044** [comment]
Can't open in multiplayer

**Comment by Bobster82** [comment]
Hi Tobias, How do you mean you can't open? Are you the server (host) or are you on a dedi server? Can you give me a bit more info to work with? 
Thank you

**Comment by Tobias0044** [comment]
On dedicated

**Comment by Bobster82** [comment]
> On dedicated

And you say you can't open? Does the mod not work or you can't open the menu? Do vehicles get repaired? Do you have admin rights on that server?

**Comment by metz1996** [comment]
Is there a UI Menu Ingame?
Or are that settings have to be changed manually in the config?

**Comment by Bobster82** [comment]
> Is there a UI Menu Ingame? Or are that settings have to be changed manually in the config?

Yes ingame menu, I added that to the latest version. Open with left alt + r ... or check your key assignments settings ;)

**Comment by metz1996** [comment]
sounds nice! i will check this out soon :)

**Comment by metz1996** [comment]
can you please implement a method for change the damage threshold and maybe the 30sec time check?

EDIT:
In Multiplayer the GUI is not possible to open as Admin. (sign in as admin)
I changed the Key to Alt + Down. It doesn't work. In Singleplayer it open correctly!

**Comment by Bobster82** [comment]
Yes I will add those. 

Maybe I need to add a debug option too to print some info to the log. 
I need to check how to get the gui working for only admin.
Does this version work on dedi? So only the menu is not working? Going to check this tonight (maybe i need to rent a server so i can check how it works haha) ;)

**Comment by metz1996** [comment]
I can't tell you that exactly atm. I think it work but I'm not sure yet because I had only some minutes to test. This evening I will try again and give more feedback. I will activate cleaning and then I will see

**Comment by metz1996** [comment]
Hi. Now i had some time to continue testing. With the new gui version it doesn't repair anymore and as i said the GUI ist not possible to open on Dedicated Server

**Comment by Bobster82** [comment]
Thanks for testing metz,
I rent myself a dedi server so I can see what is happening. The new version is not working for multiplayer how its written at the moment.
I need to learn myself some new coding skills to get the multiplayer sync going, I never dived into that part... Im still learning to program ;)

I keep u updated if I have a new version. Will do my best to get this working.

**Comment by metz1996** [comment]
no problem. You have good idea's. Don't give up ;)

**Comment by celendis** [comment]
On dedicated server, the latest mod seems to repair vehicles and may even be cleaning them after changing the settings xml. I have not tried the repaint option.  However, I also cannot open the GUI. I would like to suggest that the F1 help menu item not appear to a non-admin rather than simply not functioning.

**Comment by Bobster82** [comment]
> On dedicated server, the latest mod seems to repair vehicles and may even be cleaning them after changing the settings xml. I have not tried the repaint option. However, I also cannot open the GUI. I would like to suggest that the F1 help menu item not appear to a non-admin rather than simply not functioning.

Thanks for confirming this. I also rent a server to find out what went wrong. If you change the settings in the file, those settings aply ingame, so the server repairs/repaint/cleans.. only the menu isnt working.

Good idea to only show those commands to admins, need to find out how to do that.

Thanks you

**Comment by metz1996** [comment]
What are you meaning exactly with change the settings in the file? Do you mean if you edit it directly into the mod? Because in the mod auto repair is set as default and don't work for me. I don't have an extra Settings in modSettings folder

**Comment by celendis** [comment]
I apologize for being unclear. I meant that I edited the AutoRepair_config.xml in the savegame1 folder in order to enable the features on the dedicated server.

**Comment by Bobster82** [comment]
Hi guys, an update:
I've been working on a synchronization system (events) to get the data equal on all players/server in multiplayer game.
So far I have managed to get some data back and forth. The menu is also working now, so a new version should be out here pretty soon.

**Comment by metz1996** [comment]
Ok thanks. Now I understand what you mean with edit the file. I will check this out this evening and give feedback again. 

Thanks for your work Bobster82

**Comment by Bobster82** [comment]
New version online
