### ISSUE TITLE
Version 2.0.0.4

### ISSUE THREAD

**Issue by Bobster82** [Bobster82/FS22_AutoRepair#4]
Fixed multiplayer menu not working.
Fixed multiplayer sync.
Added option to only repair/repaint/clean.
Added option to change the time to update.
Added option to change the damage threshold.
Added option to change the wear threshold.
Added option to change the dirt threshold.

New version online. I hope this fixes all the problems.
If there are any new or existing problems, please let me know

Thanks for testing

**Comment by metz1996** [comment]
Thanks for your work! It work's perfectly now. I got an idea but i don't know how easy it would be to implement. The new options are very nice :)

Would it be possible to activate, deactivate repair/repaint/wash for every farm separately?

**Comment by Bobster82** [comment]
Nice to hear!

Yes, that can be done, I will add it to the todo list and see how and when I continue with it. I hope for xmas ;)

**Comment by metz1996** [comment]
that's cool! But you don't have to do this fast. The main features are done and they are nice. That would only be an nice extra 👍

**Comment by celendis** [comment]
Bobster, thank you for this excellent mod. In addition to separate farm settings, I would also like to suggest an option to disable autorepair for contract borrowed items and a separate option for store-leased items.  It has been working fantastic for my brother and me on our dedicated server.

**Comment by Bobster82** [comment]
> Bobster, thank you for this excellent mod. In addition to separate farm settings, I would also like to suggest an option to disable autorepair for contract borrowed items and a separate option for store-leased items. It has been working fantastic for my brother and me on our dedicated server.

Hey,
Sorry for the late comment... I had a busy time and a holiday ;)
This should be posible, don't know yet when i finish it.

@metz1996 
Work on activate, deactivate repair/repaint/wash for every farm separately is almost done (took longer to start with the project, didnt had much time), it was a lot more work. As I already said, im not a programmer, need to search a lot and trial and error ;)
